/*******************************************************************************
* File Name: MotorCurrentADC.c
* Version 2.0
*
* Description:
*  This file provides the source code to the API for the Sequencing Successive
*  Approximation ADC Component Component.
*
* Note:
*
********************************************************************************
* Copyright 2008-2014, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "MotorCurrentADC.h"


/***************************************
* Global data allocation
***************************************/
uint8 MotorCurrentADC_initVar = 0u;
volatile int16 MotorCurrentADC_offset[MotorCurrentADC_TOTAL_CHANNELS_NUM];
volatile int32 MotorCurrentADC_countsPer10Volt[MotorCurrentADC_TOTAL_CHANNELS_NUM];   /* Gain compensation */


/***************************************
* Local data allocation
***************************************/
/* Channels configuration generated by customiser */
static const uint32 CYCODE MotorCurrentADC_channelsConfig[] = { 0x00000000u };


/*******************************************************************************
* Function Name: MotorCurrentADC_Start
********************************************************************************
*
* Summary:
*  Performs all required initialization for this component
*  and enables the power. The power will be set to the appropriate
*  power based on the clock frequency.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
* Global variables:
*  The MotorCurrentADC_initVar variable is used to indicate when/if initial
*  configuration of this component has happened. The variable is initialized to
*  zero and set to 1 the first time ADC_Start() is called. This allows for
*  component Re-Start without re-initialization in all subsequent calls to the
*  MotorCurrentADC_Start() routine.
*  If re-initialization of the component is required the variable should be set
*  to zero before call of MotorCurrentADC_Start() routine, or the user may call
*  MotorCurrentADC_Init() and MotorCurrentADC_Enable() as done in the
*  MotorCurrentADC_Start() routine.
*
*******************************************************************************/
void MotorCurrentADC_Start(void)
{
    /* If not Initialized then initialize all required hardware and software */
    if(MotorCurrentADC_initVar == 0u)
    {
        MotorCurrentADC_Init();
        MotorCurrentADC_initVar = 1u;
    }
    MotorCurrentADC_Enable();
}


/*******************************************************************************
* Function Name: MotorCurrentADC_Init
********************************************************************************
*
* Summary:
*  Initialize component's parameters to the parameters set by user in the
*  customizer of the component placed onto schematic. Usually called in
*  MotorCurrentADC_Start().
*
* Parameters:
*  None.
*
* Return:
*  None.
*
* Global variables:
*  The MotorCurrentADC_offset variable is initialized.
*
*******************************************************************************/
void MotorCurrentADC_Init(void)
{
    uint32 chNum;
    uint32 tmpRegVal;
    int32 counts;

    #if(MotorCurrentADC_TOTAL_CHANNELS_NUM > 1u)
        static const uint8 CYCODE MotorCurrentADC_InputsPlacement[] =
        {
            (uint8)(MotorCurrentADC_cy_psoc4_sarmux_8__CH_0_PORT << 4u) |
            (uint8)MotorCurrentADC_cy_psoc4_sarmux_8__CH_0_PIN
            ,(uint8)(MotorCurrentADC_cy_psoc4_sarmux_8__CH_1_PORT << 4u) |
             (uint8)MotorCurrentADC_cy_psoc4_sarmux_8__CH_1_PIN
            #if(MotorCurrentADC_TOTAL_CHANNELS_NUM > 2u)
                ,(uint8)(MotorCurrentADC_cy_psoc4_sarmux_8__CH_2_PORT << 4u) |
                 (uint8)MotorCurrentADC_cy_psoc4_sarmux_8__CH_2_PIN
            #endif /* End MotorCurrentADC_TOTAL_CHANNELS_NUM > 2u */
            #if(MotorCurrentADC_TOTAL_CHANNELS_NUM > 3u)
                ,(uint8)(MotorCurrentADC_cy_psoc4_sarmux_8__CH_3_PORT << 4u) |
                 (uint8)MotorCurrentADC_cy_psoc4_sarmux_8__CH_3_PIN
            #endif /* End MotorCurrentADC_TOTAL_CHANNELS_NUM > 3u */
            #if(MotorCurrentADC_TOTAL_CHANNELS_NUM > 4u)
                ,(uint8)(MotorCurrentADC_cy_psoc4_sarmux_8__CH_4_PORT << 4u) |
                 (uint8)MotorCurrentADC_cy_psoc4_sarmux_8__CH_4_PIN
            #endif /* End MotorCurrentADC_TOTAL_CHANNELS_NUM > 4u */
            #if(MotorCurrentADC_TOTAL_CHANNELS_NUM > 5u)
                ,(uint8)(MotorCurrentADC_cy_psoc4_sarmux_8__CH_5_PORT << 4u) |
                 (uint8)MotorCurrentADC_cy_psoc4_sarmux_8__CH_5_PIN
            #endif /* End MotorCurrentADC_TOTAL_CHANNELS_NUM > 5u */
            #if(MotorCurrentADC_TOTAL_CHANNELS_NUM > 6u)
                ,(uint8)(MotorCurrentADC_cy_psoc4_sarmux_8__CH_6_PORT << 4u) |
                 (uint8)MotorCurrentADC_cy_psoc4_sarmux_8__CH_6_PIN
            #endif /* End MotorCurrentADC_TOTAL_CHANNELS_NUM > 6u */
            #if(MotorCurrentADC_TOTAL_CHANNELS_NUM > 7u)
                ,(uint8)(MotorCurrentADC_cy_psoc4_sarmux_8__CH_7_PORT << 4u) |
                 (uint8)MotorCurrentADC_cy_psoc4_sarmux_8__CH_7_PIN
            #endif /* End MotorCurrentADC_TOTAL_CHANNELS_NUM > 7u */
            #if(MotorCurrentADC_TOTAL_CHANNELS_NUM > 8u)
                ,(uint8)(MotorCurrentADC_cy_psoc4_sarmux_8__CH_8_PORT << 4u) |
                 (uint8)MotorCurrentADC_cy_psoc4_sarmux_8__CH_8_PIN
            #endif /* End MotorCurrentADC_TOTAL_CHANNELS_NUM > 8u */
        };
    #endif /* End MotorCurrentADC_TOTAL_CHANNELS_NUM > 1u */

    #if(MotorCurrentADC_IRQ_REMOVE == 0u)
        /* Start and set interrupt vector */
        CyIntSetPriority(MotorCurrentADC_INTC_NUMBER, MotorCurrentADC_INTC_PRIOR_NUMBER);
        (void)CyIntSetVector(MotorCurrentADC_INTC_NUMBER, &MotorCurrentADC_ISR);
    #endif   /* End MotorCurrentADC_IRQ_REMOVE */

    /* Init SAR and MUX registers */
    MotorCurrentADC_SAR_CHAN_EN_REG = MotorCurrentADC_DEFAULT_EN_CHANNELS;
    MotorCurrentADC_SAR_CTRL_REG = MotorCurrentADC_DEFAULT_CTRL_REG_CFG;
    MotorCurrentADC_SAR_SAMPLE_CTRL_REG = MotorCurrentADC_DEFAULT_SAMPLE_CTRL_REG_CFG;
    MotorCurrentADC_SAR_RANGE_THRES_REG = MotorCurrentADC_DEFAULT_RANGE_THRES_REG_CFG;
    MotorCurrentADC_SAR_RANGE_COND_REG  = MotorCurrentADC_COMPARE_MODE;
    MotorCurrentADC_SAR_SAMPLE_TIME01_REG = MotorCurrentADC_DEFAULT_SAMPLE_TIME01_REG_CFG;
    MotorCurrentADC_SAR_SAMPLE_TIME23_REG = MotorCurrentADC_DEFAULT_SAMPLE_TIME23_REG_CFG;
    
    /* Connect Vm to VSSA when even one channel is single-ended or multiple channels configured */
    #if(MotorCurrentADC_DEFAULT_MUX_SWITCH0 != 0u)
        MotorCurrentADC_MUX_SWITCH0_REG |= MotorCurrentADC_DEFAULT_MUX_SWITCH0;
        /* Set MUX_HW_CTRL_VSSA in MUX_SWITCH_HW_CTRL when multiple channels enabled */
        #if(MotorCurrentADC_TOTAL_CHANNELS_NUM > 1u)
            MotorCurrentADC_MUX_SWITCH_HW_CTRL_REG |= MotorCurrentADC_DEFAULT_MUX_SWITCH0;
        #endif /* MotorCurrentADC_TOTAL_CHANNELS_NUM > 1u */
    #endif /*MotorCurrentADC_CHANNELS_MODE !=0 */

    MotorCurrentADC_SAR_SATURATE_INTR_MASK_REG = 0u;
    MotorCurrentADC_SAR_RANGE_INTR_MASK_REG = 0u;
    MotorCurrentADC_SAR_INTR_MASK_REG = MotorCurrentADC_SAR_INTR_MASK;

    #if(MotorCurrentADC_CY_SAR_IP_VER == MotorCurrentADC_CY_SAR_IP_PSOC4)
        MotorCurrentADC_ANA_TRIM_REG = MotorCurrentADC_TRIM_COEF;
    #endif /* (MotorCurrentADC_CY_SAR_IP_VER == MotorCurrentADC_CY_SAR_IP_PSOC4) */

    /* Read and modify default configuration based on characterization */
    tmpRegVal = MotorCurrentADC_SAR_DFT_CTRL_REG;
    tmpRegVal &= (uint32)~MotorCurrentADC_DCEN;
    
    #if(MotorCurrentADC_CY_SAR_IP_VER == MotorCurrentADC_CY_SAR_IP_PSOC4)
        #if(MotorCurrentADC_NOMINAL_CLOCK_FREQ > (MotorCurrentADC_MAX_FREQUENCY / 2))
            tmpRegVal |= MotorCurrentADC_SEL_CSEL_DFT_CHAR;
        #else  /* clock speed < 9 Mhz */
            tmpRegVal |= MotorCurrentADC_DLY_INC;
        #endif /* clock speed > 9 Mhz */
    #else
        #if ((MotorCurrentADC_DEFAULT_VREF_SEL == MotorCurrentADC__INTERNAL1024) || \
             (MotorCurrentADC_DEFAULT_VREF_SEL == MotorCurrentADC__INTERNALVREF))
            tmpRegVal |= MotorCurrentADC_DLY_INC;
        #else
            tmpRegVal |= MotorCurrentADC_DCEN;
            tmpRegVal &= (uint32)~MotorCurrentADC_DLY_INC;
        #endif /* ((MotorCurrentADC_DEFAULT_VREF_SEL == MotorCurrentADC__INTERNAL1024) || \
                   (MotorCurrentADC_DEFAULT_VREF_SEL == MotorCurrentADC__INTERNALVREF)) */
    #endif /* (MotorCurrentADC_CY_SAR_IP_VER == MotorCurrentADC_CY_SAR_IP_PSOC4) */
    
    MotorCurrentADC_SAR_DFT_CTRL_REG = tmpRegVal;

    #if(MotorCurrentADC_MAX_RESOLUTION != MotorCurrentADC_RESOLUTION_12)
        MotorCurrentADC_WOUNDING_REG = MotorCurrentADC_ALT_WOUNDING;
    #endif /* MotorCurrentADC_MAX_RESOLUTION != MotorCurrentADC_RESOLUTION_12 */

    for(chNum = 0u; chNum < MotorCurrentADC_TOTAL_CHANNELS_NUM; chNum++)
    {
        tmpRegVal = (MotorCurrentADC_channelsConfig[chNum] & MotorCurrentADC_CHANNEL_CONFIG_MASK);
        #if(MotorCurrentADC_TOTAL_CHANNELS_NUM > 1u)
            tmpRegVal |= MotorCurrentADC_InputsPlacement[chNum];
        #endif /* End MotorCurrentADC_TOTAL_CHANNELS_NUM > 1u */
        
        
        /* When the part is limited to 10-bit then the SUB_RESOLUTION bit
        *  will be ignored and the RESOLUTION bit selects between 10-bit
        *  (0) and 8-bit (1) resolution.
        */
        #if((MotorCurrentADC_MAX_RESOLUTION != MotorCurrentADC_RESOLUTION_12) && \
            (MotorCurrentADC_ALT_WOUNDING == MotorCurrentADC_WOUNDING_10BIT))
            tmpRegVal &= (uint32)(~MotorCurrentADC_ALT_RESOLUTION_ON);
        #endif /* MotorCurrentADC_MAX_RESOLUTION != MotorCurrentADC_RESOLUTION_12 */

        #if(MotorCurrentADC_INJ_CHANNEL_ENABLED)
        if(chNum < MotorCurrentADC_SEQUENCED_CHANNELS_NUM)
        #endif /* MotorCurrentADC_INJ_CHANNEL_ENABLED */
        {
            CY_SET_REG32((reg32 *)(MotorCurrentADC_SAR_CHAN_CONFIG_IND + (uint32)(chNum << 2)), tmpRegVal);

            if((MotorCurrentADC_channelsConfig[chNum] & MotorCurrentADC_IS_SATURATE_EN_MASK) != 0u)
            {
                MotorCurrentADC_SAR_SATURATE_INTR_MASK_REG |= (uint16)((uint16)1 << chNum);
            }

            if((MotorCurrentADC_channelsConfig[chNum] & MotorCurrentADC_IS_RANGE_CTRL_EN_MASK) != 0u)
            {
                MotorCurrentADC_SAR_RANGE_INTR_MASK_REG |= (uint16)((uint16)1 << chNum);
            }
        }
        #if(MotorCurrentADC_INJ_CHANNEL_ENABLED)
            else
            {
                CY_SET_REG32(MotorCurrentADC_SAR_INJ_CHAN_CONFIG_PTR, tmpRegVal | MotorCurrentADC_INJ_TAILGATING);

                if((MotorCurrentADC_channelsConfig[chNum] & MotorCurrentADC_IS_SATURATE_EN_MASK) != 0u)
                {
                    MotorCurrentADC_SAR_INTR_MASK_REG |= MotorCurrentADC_INJ_SATURATE_MASK;
                }

                if((MotorCurrentADC_channelsConfig[chNum] & MotorCurrentADC_IS_RANGE_CTRL_EN_MASK) != 0u)
                {
                    MotorCurrentADC_SAR_INTR_MASK_REG |= MotorCurrentADC_INJ_RANGE_MASK;
                }
            }
        #endif /* MotorCurrentADC_INJ_CHANNEL_ENABLED */

        if((MotorCurrentADC_channelsConfig[chNum] & MotorCurrentADC_ALT_RESOLUTION_ON) != 0u)
        {
               counts = (int32)MotorCurrentADC_DEFAULT_MAX_WRK_ALT;
        }
        else
        {
               counts = (int32)MotorCurrentADC_SAR_WRK_MAX_12BIT;
        }

        if((MotorCurrentADC_channelsConfig[chNum] & MotorCurrentADC_DIFFERENTIAL_EN) == 0u)
        {
            #if((MotorCurrentADC_DEFAULT_SE_RESULT_FORMAT_SEL == MotorCurrentADC__FSIGNED) && \
                (MotorCurrentADC_DEFAULT_NEG_INPUT_SEL == MotorCurrentADC__VREF))
                /* Set offset to the minus half scale to convert results to unsigned format */
                MotorCurrentADC_offset[chNum] = (int16)(counts / -2);
            #else
                MotorCurrentADC_offset[chNum] = 0;
            #endif /* end DEFAULT_SE_RESULT_FORMAT_SEL == MotorCurrentADC__FSIGNED */
        }
        else    /* Differential channel */
        {
            #if(MotorCurrentADC_DEFAULT_DIFF_RESULT_FORMAT_SEL == MotorCurrentADC__FUNSIGNED)
                /* Set offset to the half scale to convert results to signed format */
                MotorCurrentADC_offset[chNum] = (int16)(counts / 2);
            #else
                MotorCurrentADC_offset[chNum] = 0;
            #endif /* end MotorCurrentADC_DEFAULT_DIFF_RESULT_FORMAT_SEL == MotorCurrentADC__FUNSIGNED */
        }
        /* Calculate gain in counts per 10 volts with rounding */
        MotorCurrentADC_countsPer10Volt[chNum] = (int16)(((counts * MotorCurrentADC_10MV_COUNTS) +
                            MotorCurrentADC_DEFAULT_VREF_MV_VALUE) / (MotorCurrentADC_DEFAULT_VREF_MV_VALUE * 2));
    }
}

/*******************************************************************************
* Function Name: ADC_SAR_1_Enable
********************************************************************************
*
* Summary:
*  Enables the clock and analog power for SAR ADC.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void MotorCurrentADC_Enable(void)
{
    if (0u == (MotorCurrentADC_SAR_CTRL_REG & MotorCurrentADC_ENABLE))
    {
        #if(MotorCurrentADC_CY_SAR_IP_VER != MotorCurrentADC_CY_SAR_IP_PSOC4)

            while (0u != (MotorCurrentADC_SAR_STATUS_REG & MotorCurrentADC_STATUS_BUSY))
            {
                /* wait for SAR to go idle for to avoid deadlock */
            }
        #endif /* (MotorCurrentADC_CY_SAR_IP_VER != MotorCurrentADC_CY_SAR_IP_PSOC4) */
        
        MotorCurrentADC_SAR_CTRL_REG |= MotorCurrentADC_ENABLE;
        
        /* The block is ready to use 10 us after the enable signal is set high. */
        CyDelayUs(MotorCurrentADC_10US_DELAY);         
    }
}


/*******************************************************************************
* Function Name: MotorCurrentADC_Stop
********************************************************************************
*
* Summary:
*  This function stops ADC conversions and puts the ADC into its lowest power
*  mode.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void MotorCurrentADC_Stop(void)
{
    MotorCurrentADC_SAR_CTRL_REG &= (uint32)~MotorCurrentADC_ENABLE;
}


/*******************************************************************************
* Function Name: MotorCurrentADC_StartConvert
********************************************************************************
*
* Summary:
*  Description:
*  For free running mode, this API starts the conversion process and it
*  runs continuously.
*
*  In a triggered mode, this routine triggers every conversion by
*  writing into the FW_TRIGGER bit in SAR_START_CTRL reg. In triggered mode,
*  every conversion has to start by this API.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void MotorCurrentADC_StartConvert(void)
{
    #if(MotorCurrentADC_DEFAULT_SAMPLE_MODE_SEL == MotorCurrentADC__FREERUNNING)
        MotorCurrentADC_SAR_SAMPLE_CTRL_REG |= MotorCurrentADC_CONTINUOUS_EN;
    #else /* Firmware trigger */
        MotorCurrentADC_SAR_START_CTRL_REG = MotorCurrentADC_FW_TRIGGER;
    #endif /* End MotorCurrentADC_DEFAULT_SAMPLE_MODE == MotorCurrentADC__FREERUNNING */

}


/*******************************************************************************
* Function Name: MotorCurrentADC_StopConvert
********************************************************************************
*
* Summary:
*  Forces the ADC to stop all conversions.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void MotorCurrentADC_StopConvert(void)
{
    #if(MotorCurrentADC_DEFAULT_SAMPLE_MODE_SEL == MotorCurrentADC__FREERUNNING)
        MotorCurrentADC_SAR_SAMPLE_CTRL_REG &= (uint32)(~MotorCurrentADC_CONTINUOUS_EN);
    #endif /* MotorCurrentADC_DEFAULT_SAMPLE_MODE == MotorCurrentADC__FREERUNNING */
}


/*******************************************************************************
* Function Name: MotorCurrentADC_IsEndConversion
********************************************************************************
*
* Summary:
*  Description: Checks for ADC end of conversion for the case one
*  channel and end of scan for the case of multiple channels. It acts
*  as a software version of the EOC. This function provides the
*  programmer with two options. In one mode this function
*  immediately returns with the conversion status. In the other mode,
*  the function does not return (blocking) until the conversion has
*  completed.
*
* Parameters:
*  ADC_RETURN_STATUS        -> Immediately returns conversion result status
*  ADC_WAIT_FOR_RESULT      -> Does not return until ADC complete
*  ADC_RETURN_STATUS_INJ    -> Immediately returns conversion result status
*                              for injection channel
*  ADC_WAIT_FOR_RESULT_INJ  -> Does not return until ADC completes injection
*                              channel conversion
*
* Return:
*  If a non-zero value is returned, the last conversion or scan has completed.
*  If the returned value is zero, the ADC is still in the process of a scan.
*
*******************************************************************************/
uint32 MotorCurrentADC_IsEndConversion(uint32 retMode)
{
    uint32 status = 0u;

    if((retMode & (MotorCurrentADC_RETURN_STATUS | MotorCurrentADC_WAIT_FOR_RESULT)) != 0u)
    {
        do
        {
            status = MotorCurrentADC_SAR_INTR_REG & MotorCurrentADC_EOS_MASK;
        }while((status == 0u) && ((retMode & MotorCurrentADC_WAIT_FOR_RESULT) != 0u));

        if(status != 0u)
        {
            /* Clear EOS bit */
            MotorCurrentADC_SAR_INTR_REG = MotorCurrentADC_EOS_MASK;
        }
    }

    #if(MotorCurrentADC_INJ_CHANNEL_ENABLED)
        if((retMode & (MotorCurrentADC_RETURN_STATUS_INJ | MotorCurrentADC_WAIT_FOR_RESULT_INJ)) != 0u)
        {
            do
            {
                status |= MotorCurrentADC_SAR_INTR_REG & MotorCurrentADC_INJ_EOC_MASK;
            }while(((status & MotorCurrentADC_INJ_EOC_MASK) == 0u) &&
                   ((retMode & MotorCurrentADC_WAIT_FOR_RESULT_INJ) != 0u));

            if((status & MotorCurrentADC_INJ_EOC_MASK) != 0u)
            {
                /* Clear Injection EOS bit */
                MotorCurrentADC_SAR_INTR_REG = MotorCurrentADC_INJ_EOC_MASK;
            }
        }
    #endif /* MotorCurrentADC_INJ_CHANNEL_ENABLED */

    return (status);
}


/*******************************************************************************
* Function Name: MotorCurrentADC_GetResult16
********************************************************************************
*
* Summary:
*  Gets the data available in the SAR DATA register.
*
* Parameters:
*  chan: The ADC channel in which to return the result. The first channel
*  is 0 and the injection channel if enabled is the number of valid channels.
*
* Return:
*  Returns converted data as a signed 16-bit integer
*
*******************************************************************************/
int16 MotorCurrentADC_GetResult16(uint32 chan)
{
    uint32 result;

    /* Halt CPU in debug mode if channel is out of valid range */
    CYASSERT(chan < MotorCurrentADC_TOTAL_CHANNELS_NUM);

    if(chan < MotorCurrentADC_SEQUENCED_CHANNELS_NUM)
    {
        result = CY_GET_REG32((reg32 *)(MotorCurrentADC_SAR_CHAN_RESULT_IND + (uint32)(chan << 2u))) &
                MotorCurrentADC_RESULT_MASK;
    }
    else
    {
        #if(MotorCurrentADC_INJ_CHANNEL_ENABLED)
            result = MotorCurrentADC_SAR_INJ_RESULT_REG & MotorCurrentADC_RESULT_MASK;
        #else
            result = 0u;
        #endif /* MotorCurrentADC_INJ_CHANNEL_ENABLED */
    }

    return ( (int16)result );
}


/*******************************************************************************
* Function Name: MotorCurrentADC_SetChanMask
********************************************************************************
*
* Summary:
*  Sets the channel enable mask.
*
* Parameters:
*  mask: Sets which channels that will be
*  scanned. Setting bits for channels that do not exist will have no
*  effect. For example, if only 6 channels were enabled, setting a
*  mask of 0x0103 would only enable the last two channels (0 and 1).
*  This API will not enable the injection channel.
*  Examples: If the component is setup to sequence through 8
*  channels, a mask of 0x000F would enable channels 0, 1, 2, and 3.
*
* Return:
*  None.
*
*******************************************************************************/
void MotorCurrentADC_SetChanMask(uint32 mask)
{
    MotorCurrentADC_SAR_CHAN_EN_REG = mask & MotorCurrentADC_MAX_CHANNELS_EN_MASK;
}

#if(MotorCurrentADC_INJ_CHANNEL_ENABLED)


    /*******************************************************************************
    * Function Name: MotorCurrentADC_EnableInjection
    ********************************************************************************
    *
    * Summary:
    *  Enables the injection channel for the next scan only.
    *
    * Parameters:
    *  None.
    *
    * Return:
    *  None.
    *
    *******************************************************************************/
    void MotorCurrentADC_EnableInjection(void)
    {
        MotorCurrentADC_SAR_INJ_CHAN_CONFIG_REG |= MotorCurrentADC_INJ_CHAN_EN;
    }

#endif /* MotorCurrentADC_INJ_CHANNEL_ENABLED */


/*******************************************************************************
* Function Name: MotorCurrentADC_SetLowLimit
********************************************************************************
*
* Summary:
*  Sets the low limit parameter for a limit condition.
*
* Parameters:
*  lowLimit: The low limit for a limit condition.
*
* Return:
*  None.
*
*******************************************************************************/
void MotorCurrentADC_SetLowLimit(uint32 lowLimit)
{
    MotorCurrentADC_SAR_RANGE_THRES_REG &= (uint32)(~MotorCurrentADC_RANGE_LOW_MASK);
    MotorCurrentADC_SAR_RANGE_THRES_REG |= lowLimit & MotorCurrentADC_RANGE_LOW_MASK;
}


/*******************************************************************************
* Function Name: MotorCurrentADC_SetHighLimit
********************************************************************************
*
* Summary:
*  Sets the low limit parameter for a limit condition.
*
* Parameters:
*  highLimit: The high limit for a limit condition.
*
* Return:
*  None.
*
*******************************************************************************/
void MotorCurrentADC_SetHighLimit(uint32 highLimit)
{
    MotorCurrentADC_SAR_RANGE_THRES_REG &= (uint32)(~MotorCurrentADC_RANGE_HIGH_MASK);
    MotorCurrentADC_SAR_RANGE_THRES_REG |= (uint32)(highLimit << MotorCurrentADC_RANGE_HIGH_OFFSET);
}


/*******************************************************************************
* Function Name: MotorCurrentADC_SetLimitMask
********************************************************************************
*
* Summary:
*  Sets the channel limit condition mask.
*
* Parameters:
*  mask: Sets which channels that may cause a
*  limit condition interrupt. Setting bits for channels that do not exist
*  will have no effect. For example, if only 6 channels were enabled,
*  setting a mask of 0x0103 would only enable the last two channels (0 and 1).
*
* Return:
*  None.
*
*******************************************************************************/
void MotorCurrentADC_SetLimitMask(uint32 mask)
{
    MotorCurrentADC_SAR_RANGE_INTR_MASK_REG = mask & MotorCurrentADC_MAX_CHANNELS_EN_MASK;
}


/*******************************************************************************
* Function Name: MotorCurrentADC_SetSatMask
********************************************************************************
*
* Summary:
*  Sets the channel saturation event mask.
*
* Parameters:
*  mask: Sets which channels that may cause a
*  saturation event interrupt. Setting bits for channels that do not exist
*  will have no effect. For example, if only 8 channels were enabled,
*  setting a mask of 0x01C0 would only enable two channels (6 and 7).
*
* Return:
*  None.
*
*******************************************************************************/
void MotorCurrentADC_SetSatMask(uint32 mask)
{
    MotorCurrentADC_SAR_SATURATE_INTR_MASK_REG = mask & MotorCurrentADC_MAX_CHANNELS_EN_MASK;
}


/*******************************************************************************
* Function Name: MotorCurrentADC_SetOffset
********************************************************************************
*
* Summary:
*   Description: Sets the ADC offset which is used by the functions
*   ADC_CountsTo_uVolts, ADC_CountsTo_mVolts and ADC_CountsTo_Volts
*   to substract the offset from the given reading
*   before calculating the voltage conversion.
*
* Parameters:
*  chan: ADC channel number.
*  offset: This value is a measured value when the
*          inputs are shorted or connected to the same input voltage.
*
* Return:
*  None.
*
* Global variables:
*  MotorCurrentADC_Offset:  Modified to set the user provided offset.
*
*******************************************************************************/
void MotorCurrentADC_SetOffset(uint32 chan, int16 offset)
{
    /* Halt CPU in debug mode if channel is out of valid range */
    CYASSERT(chan < MotorCurrentADC_TOTAL_CHANNELS_NUM);

    MotorCurrentADC_offset[chan] = offset;
}


/*******************************************************************************
* Function Name: MotorCurrentADC_SetGain
********************************************************************************
*
* Summary:
*  Description: Sets the ADC gain in counts per 10 volt for the voltage
*  conversion functions below. This value is set by default by the
*  reference and input range settings. It should only be used to further
*  calibrate the ADC with a known input or if an external reference is
*  used. Affects the ADC_CountsTo_uVolts, ADC_CountsTo_mVolts
*  and ADC_CountsTo_Volts functions by supplying the correct
*  conversion between ADC counts and voltage.
*
* Parameters:
*  chan: ADC channel number.
*  adcGain: ADC gain in counts per 10 volts.
*
* Return:
*  None.
*
* Global variables:
*  MotorCurrentADC_CountsPer10Volt:  modified to set the ADC gain in counts
*   per 10 volt.
*
*******************************************************************************/
void MotorCurrentADC_SetGain(uint32 chan, int32 adcGain)
{
    /* Halt CPU in debug mode if channel is out of valid range */
    CYASSERT(chan < MotorCurrentADC_TOTAL_CHANNELS_NUM);

    MotorCurrentADC_countsPer10Volt[chan] = adcGain;
}


#if(MotorCurrentADC_DEFAULT_JUSTIFICATION_SEL == MotorCurrentADC__RIGHT)


    /*******************************************************************************
    * Function Name: MotorCurrentADC_CountsTo_mVolts
    ********************************************************************************
    *
    * Summary:
    *  This function converts ADC counts to mVolts
    *  This function is not available when left data format justification selected.
    *
    * Parameters:
    *  chan: The ADC channel number.
    *  adcCounts: Result from the ADC conversion
    *
    * Return:
    *  Results in mVolts
    *
    * Global variables:
    *  MotorCurrentADC_countsPer10Volt:  used to convert ADC counts to mVolts.
    *  MotorCurrentADC_Offset:  Used as the offset while converting ADC counts
    *   to mVolts.
    *
    *******************************************************************************/
    int16 MotorCurrentADC_CountsTo_mVolts(uint32 chan, int16 adcCounts)
    {
        int16 mVolts;

        /* Halt CPU in debug mode if channel is out of valid range */
        CYASSERT(chan < MotorCurrentADC_TOTAL_CHANNELS_NUM);

        /* Divide the adcCount when accumulate averaging mode selected */
        #if(MotorCurrentADC_DEFAULT_AVG_MODE == MotorCurrentADC__ACCUMULATE)
            if((MotorCurrentADC_channelsConfig[chan] & MotorCurrentADC_AVERAGING_EN) != 0u)
            {
                adcCounts /= MotorCurrentADC_DEFAULT_AVG_SAMPLES_DIV;
            }
        #endif /* MotorCurrentADC_DEFAULT_AVG_MODE == MotorCurrentADC__ACCUMULATE */

        /* Subtract ADC offset */
        adcCounts -= MotorCurrentADC_offset[chan];

        mVolts = (int16)((((int32)adcCounts * MotorCurrentADC_10MV_COUNTS) + ( (adcCounts > 0) ?
                 (MotorCurrentADC_countsPer10Volt[chan] / 2) : (-(MotorCurrentADC_countsPer10Volt[chan] / 2)) ))
                 / MotorCurrentADC_countsPer10Volt[chan]);

        return( mVolts );
    }


    /*******************************************************************************
    * Function Name: MotorCurrentADC_CountsTo_uVolts
    ********************************************************************************
    *
    * Summary:
    *  This function converts ADC counts to micro Volts
    *  This function is not available when left data format justification selected.
    *
    * Parameters:
    *  chan: The ADC channel number.
    *  adcCounts: Result from the ADC conversion
    *
    * Return:
    *  Results in uVolts
    *
    * Global variables:
    *  MotorCurrentADC_countsPer10Volt:  used to convert ADC counts to uVolts.
    *  MotorCurrentADC_Offset:  Used as the offset while converting ADC counts
    *   to mVolts.
    *
    * Theory:
    *  Care must be taken to not exceed the maximum value for a 31 bit signed
    *  number in the conversion to uVolts and at the same time not loose
    *  resolution.
    *  To convert adcCounts to microVolts it is required to be multiplied
    *  on 10 million and later divide on gain in counts per 10V.
    *
    *******************************************************************************/
    int32 MotorCurrentADC_CountsTo_uVolts(uint32 chan, int16 adcCounts)
    {
        int64 uVolts;

        /* Halt CPU in debug mode if channel is out of valid range */
        CYASSERT(chan < MotorCurrentADC_TOTAL_CHANNELS_NUM);

        /* Divide the adcCount when accumulate averaging mode selected */
        #if(MotorCurrentADC_DEFAULT_AVG_MODE == MotorCurrentADC__ACCUMULATE)
            if((MotorCurrentADC_channelsConfig[chan] & MotorCurrentADC_AVERAGING_EN) != 0u)
            {
                adcCounts /= MotorCurrentADC_DEFAULT_AVG_SAMPLES_DIV;
            }
        #endif /* MotorCurrentADC_DEFAULT_AVG_MODE == MotorCurrentADC__ACCUMULATE */

        /* Subtract ADC offset */
        adcCounts -= MotorCurrentADC_offset[chan];

        uVolts = ((int64)adcCounts * MotorCurrentADC_10UV_COUNTS) / MotorCurrentADC_countsPer10Volt[chan];

        return( (int32)uVolts );
    }


    /*******************************************************************************
    * Function Name: MotorCurrentADC_CountsTo_Volts
    ********************************************************************************
    *
    * Summary:
    *  Converts the ADC output to Volts as a floating point number.
    *  This function is not available when left data format justification selected.
    *
    * Parameters:
    *  chan: The ADC channel number.
    *  Result from the ADC conversion
    *
    * Return:
    *  Results in Volts
    *
    * Global variables:
    *  MotorCurrentADC_countsPer10Volt:  used to convert ADC counts to Volts.
    *  MotorCurrentADC_Offset:  Used as the offset while converting ADC counts
    *   to mVolts.
    *
    *******************************************************************************/
    float32 MotorCurrentADC_CountsTo_Volts(uint32 chan, int16 adcCounts)
    {
        float32 volts;

        /* Halt CPU in debug mode if channel is out of valid range */
        CYASSERT(chan < MotorCurrentADC_TOTAL_CHANNELS_NUM);

        /* Divide the adcCount when accumulate averaging mode selected */
        #if(MotorCurrentADC_DEFAULT_AVG_MODE == MotorCurrentADC__ACCUMULATE)
            if((MotorCurrentADC_channelsConfig[chan] & MotorCurrentADC_AVERAGING_EN) != 0u)
            {
                adcCounts /= MotorCurrentADC_DEFAULT_AVG_SAMPLES_DIV;
            }
        #endif /* MotorCurrentADC_DEFAULT_AVG_MODE == MotorCurrentADC__ACCUMULATE */

        /* Subtract ADC offset */
        adcCounts -= MotorCurrentADC_offset[chan];

        volts = ((float32)adcCounts * MotorCurrentADC_10V_COUNTS) / (float32)MotorCurrentADC_countsPer10Volt[chan];

        return( volts );
    }

#endif /* End MotorCurrentADC_DEFAULT_JUSTIFICATION_SEL == MotorCurrentADC__RIGHT */


/* [] END OF FILE */
