/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 Component Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <ModbusUART.h>
#include <ModbusUART_SPI_UART.h>
#include <ModbusUART_PINS.h>
#include <ModbusUART_SPI_UART_PVT.h>
#include <ModbusUART_PVT.h>
#include <ModbusUART_BOOT.h>
#include <TX_LED.h>
#include <TX_LED_aliases.h>
#include <RX_LED.h>
#include <RX_LED_aliases.h>
#include <MessageReceived.h>
#include <TimerPin.h>
#include <TimerPin_aliases.h>
#include <EndOfMessage.h>
#include <P0_2_LED.h>
#include <P0_2_LED_aliases.h>
#include <writeEnable.h>
#include <writeEnable_aliases.h>
#include <MessageTimer.h>
#include <MessageTimerClock.h>
#include <ChannelA.h>
#include <ChannelA_aliases.h>
#include <ChannelB.h>
#include <ChannelB_aliases.h>
#include <EncoderInterruptPin.h>
#include <EncoderInterruptPin_aliases.h>
#include <EncoderInterrupt.h>
#include <timer_clock.h>
#include <SpeedTimer.h>
#include <SpeedInterrupt.h>
#include <PWMOutput.h>
#include <PWMOutput_aliases.h>
#include <MotorPWM.h>
#include <PWMClock.h>
#include <Direction.h>
#include <Direction_aliases.h>
#include <MotorCurrentADC.h>
#include <MotorCurrentPin.h>
#include <MotorCurrentPin_aliases.h>
#include <ModbusUART_SCBCLK.h>
#include <ModbusUART_tx.h>
#include <ModbusUART_tx_aliases.h>
#include <ModbusUART_rx.h>
#include <ModbusUART_rx_aliases.h>
#include <MotorCurrentADC_IRQ.h>
#include <MotorCurrentADC_intClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

